// git add , git summit, git push 
//
//이거 끝내면 프리 코드캠프 끝내기
//맨날 코드 보내기 그리고 인터넷에 올리기 


// 시작하기 전에 로직 먼저 만들기 
//1.
//2.
//3.
//4.

// 0. 시작하기 전에 문제 로직 먼저 만들기
// 1. 피보나치 + freecodecamp 나머지 문제 물기;
// 2. 맨날 코드 보내기 / 인터넷에 올리기

//Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

//logic 1:유저가 부른 숫자까지 도는 루프 만들기
//lpgic 2: 피보나치 만들기
//logic 3:유저가 10을 입력하면 10 아니면 이하로 나오게 하기
//logic 4: 짝수를 더하게 하는 코드 만들기

function fiboEvenSum(n) {
    let zero = 0;
    var result;
    var a;
    var b;
    a = 0;
    b = 1;
    let addingNumber = 0;
    result = b;
    for (var i = 1; i <= n; i++) {

        result = a + b;
        a = b;
        b = result;
        // console.log(result);

        if (result <= n) {
            // zero = 0;
            result += zero;
            //console.log(result);
            if (result % 2 == 0) {

                //result += zero;
                //  addingNumber = 0;
                addingNumber  += result;
              
            }
            // console.log(addingNumber);
             
        }
      
        // 여기서 짝수끼리 더하는 코드 만들어야되는데.

    }


    return addingNumber;
    //왜 리턴을 result로 해도 안될까 
}
console.log(fiboEvenSum(10));



//정리된 버전

function fiboEvenSum(n) {
    var result;
    var a = 0;
    var b = 1;
    let addingNumber = 0;
    for (var i = 1; i <= n; i++) {
        result = a + b; // 0 1 = 1
        a = b;
        b = result;

        if (result <= n) {
            if (result % 2 == 0) {
                addingNumber += result;
            }
        }
    }
    return addingNumber;
}
console.log(fiboEvenSum(10));

