// git add , git summit, git push 
//
//이거 끝내면 프리 코드캠프 끝내기
//맨날 코드 보내기 그리고 인터넷에 올리기 


// 시작하기 전에 로직 먼저 만들기 
//1.
//2.
//3.
//4.

// 0. 시작하기 전에 문제 로직 먼저 만들기
// 1. 피보나치 + freecodecamp 나머지 문제 물기;
// 2. 맨날 코드 보내기 / 인터넷에 올리기

//Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

//logic 1:유저가 부른 숫자까지 도는 루프 만들기
//lpgic 2: 피보나치 만들기
//logic 2:짝수 숫자들 찾아내는 코드 적기
//logic 3:짝수 숫자들 나오게 하는 코드를 피보나치에 나오는 짝수들로 연결시키기
//logic 4:
let zero = 0;
function fiboEvenSum(n) {

    var result, a, b;
     a = 0;
     b = 1;
     
    result = b;
    for (var i = 1; i <= n; i++) {
        console.log(result);
        result = a + b;
        a = b;
        b = result;
    }
    

    for (let i = 1; i <= n; i++) {
        if (result % 2 == 0) {
            zero += i;
            // console.log(zero);
        }
    }
// console.log(zero);
    return true;
}
fiboEvenSum(10)

